#!/bin/sh
# live-build auto configuration
set -e

# Load defaults if not set in env
LB_DISTRIBUTION="${DISTRIBUTION:-trixie}"
LB_ARCHITECTURES="${ARCHITECTURE:-amd64}"
LB_ARCHIVE_AREAS="${ARCHIVE_AREAS:-main contrib non-free non-free-firmware}"
LB_HOSTNAME="${HOSTNAME:-deapx}"
LB_LIVE_USERNAME="${LIVE_USERNAME:-deapx}"

lb config \
    --mode debian \
    --system live \
    --distribution "${LB_DISTRIBUTION}" \
    --archive-areas "${LB_ARCHIVE_AREAS}" \
    --architectures "${LB_ARCHITECTURES}" \
    --binary-images iso-hybrid \
    --bootloaders "grub-efi syslinux" \
    --debian-installer "${LB_DEBIAN_INSTALLER:-false}" \
    --apt-indices "${LB_APT_INDICES:-false}" \
    --apt-recommends "${LB_APT_RECOMMENDS:-true}" \
    --linux-packages "${KERNEL_PACKAGES:-linux-image-amd64}" \
    --linux-flavours "${LB_LINUX_FLAVOURS:-amd64}" \
    --firmware-chroot "${LB_FIRMWARE_CHROOT:-true}" \
    --firmware-binary "${LB_FIRMWARE_BINARY:-true}" \
    --memtest "${LB_MEMTEST:-none}" \
    --win32-loader "${LB_WIN32_LOADER:-false}" \
    --initramfs-compression "${LB_INITRAMFS_COMPRESSION:-gzip}" \
    --security "${LB_SECURITY:-true}" \
    --updates "${LB_UPDATES:-true}" \
    --backports "${LB_BACKPORTS:-false}" \
    --hostname "${LB_HOSTNAME}" \
    --iso-application "DeapX OS" \
    --iso-preparer "DeapX Project" \
    --iso-publisher "DeapX Project" \
    --iso-volume "DeapX OS ${LB_DISTRIBUTION}" \
    --bootappend-live "boot=live components quiet splash username=${LB_LIVE_USERNAME} hostname=${LB_HOSTNAME}" \
    --mirror-bootstrap "http://deb.debian.org/debian/" \
    --mirror-chroot "http://deb.debian.org/debian/" \
    --mirror-chroot-security "http://security.debian.org/debian-security/" \
    --mirror-binary "http://deb.debian.org/debian/" \
    --mirror-debian-installer "http://deb.debian.org/debian/"
