#!/usr/bin/env bash
# DeapX OS — configure live-build
set -euo pipefail
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"
load_config "${ROOT_DIR}/config/build.conf"

link_build_inputs() {
    local item
    for item in hooks includes.chroot package-lists; do
        if [[ ! -d "${ROOT_DIR}/${item}" ]]; then
            die "Required directory missing: ${item}/"
        fi
        mkdir -p "${ROOT_DIR}/config"
        rm -f "${ROOT_DIR}/config/${item}"
        # Create relative symlinks for portability
        ln -sfn "../${item}" "${ROOT_DIR}/config/${item}"
    done
}

install_auto_scripts() {
    mkdir -p "${ROOT_DIR}/config/auto"
    install -m 0755 "${ROOT_DIR}/auto/config" "${ROOT_DIR}/config/auto/config"
    install -m 0755 "${ROOT_DIR}/auto/clean" "${ROOT_DIR}/config/auto/clean"
}

generate_chroot_env() {
    local env_file="${ROOT_DIR}/includes.chroot/usr/share/deapx/build.env"
    log_info "Generating chroot environment file: ${env_file}"
    mkdir -p "$(dirname "${env_file}")"
    cat > "${env_file}" <<EOF
# DeapX OS Build Environment variables
# Sourced by chroot hooks during build. Generated by configure.sh.
DISTRIBUTION="${DISTRIBUTION}"
ARCHITECTURE="${ARCHITECTURE}"
LIVE_USERNAME="${LIVE_USERNAME}"
LIVE_FULLNAME="${LIVE_FULLNAME}"
LIVE_PASSWORD="${LIVE_PASSWORD}"
HOSTNAME="${HOSTNAME}"
DOMAINNAME="${DOMAINNAME}"
LOCALE_DEFAULT="${LOCALE_DEFAULT}"
KEYMAP="${KEYMAP}"
PLYMOUTH_THEME="${PLYMOUTH_THEME}"
EOF
}

main() {
    log_info "Configuring live-build..."
    cd "${ROOT_DIR}"
    export_debian_env
    link_build_inputs
    install_auto_scripts
    generate_chroot_env
    lb config
    if [[ ! -f "${ROOT_DIR}/config/bootstrap" ]]; then
        die "lb config did not produce config/bootstrap"
    fi
    log_info "live-build configured for ${DISTRIBUTION}/${ARCHITECTURE}."
}

main "$@"
